// ==========================================
//  WORDTIDE — WORD DATABASE
//
//  Rules enforced in this file:
//    • No word appears in more than one topic
//    • No word appears twice within the same topic
//    • No topic word also appears in dailyWords
//    • All words are UPPERCASE
// ==========================================

const WORD_DB = {
  topics: [
    {
      id: "nature",
      name: "Nature",
      emoji: "🌿",
      hint: "Found in the natural world",
      words: [
        { word: "RIVER",    hint: "Flows through valleys" },
        { word: "STORM",    hint: "Nature's fury" },
        { word: "BLOOM",    hint: "A flower's moment" },
        { word: "FROST",    hint: "Winter's touch" },
        { word: "GROVE",    hint: "A cluster of trees" },
        { word: "THORN",    hint: "A rose's defense" },
        { word: "CREEK",    hint: "A small flowing water" },
        { word: "CLIFF",    hint: "Edge of stone" },
        { word: "BIRCH",    hint: "White-barked tree" },
        { word: "FUNGI",    hint: "Forest floor dwellers" },
        { word: "DELTA",    hint: "Where a river meets the sea" },
        { word: "ALGAE",    hint: "Ocean's green carpet" },
        { word: "MAGMA",    hint: "Earth's inner fire" },
        { word: "QUARTZ",   hint: "A common mineral" },
        { word: "RAPIDS",   hint: "A river in a hurry" },
        { word: "CANOPY",   hint: "Jungle's roof" },
        { word: "POLLEN",   hint: "The dust of flowers" },
        { word: "LICHEN",   hint: "Rock and bark dweller" },
        { word: "GEYSER",   hint: "Earth's hot spring eruption" },
        { word: "CAVERN",   hint: "A large underground cave" },
        { word: "MEADOW",   hint: "An open grassy field" },
        { word: "FERN",     hint: "Ancient leafy plant" },
        { word: "PEBBLE",   hint: "A small smooth stone" },
        { word: "SEDGE",    hint: "Grass-like wetland plant" },
        { word: "MARSH",    hint: "Wet low-lying land" },
        { word: "GLACIER",  hint: "A slow river of ice" },
        { word: "TUNDRA",   hint: "Frozen treeless plain" },
        { word: "MONSOON",  hint: "Season of heavy rain" },
        { word: "RAVINE",   hint: "A narrow steep-sided valley" },
        { word: "ICICLE",   hint: "Frozen drip from a roof" },
        { word: "PEAT",     hint: "Decomposed plant matter in bogs" },
        { word: "STALACTITE", hint: "Hangs from a cave ceiling" },
        { word: "COBALT",   hint: "A vivid blue mineral" },
        { word: "BASALT",   hint: "Dark volcanic rock" },
        { word: "FLINT",    hint: "Stone that sparks" },
        { word: "SILT",     hint: "Fine river sediment" },
        { word: "GALE",     hint: "A fierce wind" },
        { word: "SPORE",    hint: "A fern's seed equivalent" },
        { word: "LOAM",     hint: "Rich fertile soil" },
        { word: "HEATH",    hint: "Open shrubby moorland" },
        { word: "VALE",     hint: "A gentle valley" },
        { word: "MESA",     hint: "A flat-topped hill" },
        { word: "SHOAL",    hint: "A shallow sandbank" },
        { word: "DUSK",     hint: "The end of daylight" },
        { word: "AMBER",    hint: "Fossilised tree resin" },
        { word: "CIRRUS",   hint: "Wispy high-altitude cloud" },
        { word: "CUMULUS",  hint: "Fluffy heaped cloud" },
        { word: "TALON",    hint: "A bird of prey's claw" },
        { word: "BURROW",   hint: "An animal's underground home" },
        { word: "DUNE",     hint: "A hill of wind-blown sand" },
      ],
    },
    {
      id: "ocean",
      name: "Ocean",
      emoji: "🌊",
      hint: "Life beneath the waves",
      words: [
        { word: "WHALE",    hint: "Ocean's gentle giant" },
        { word: "CORAL",    hint: "Reef builder" },
        { word: "SHARK",    hint: "Apex predator" },
        { word: "SQUID",    hint: "Eight-armed sprinter" },
        { word: "KELP",     hint: "Underwater forest" },
        { word: "PRAWN",    hint: "Pink and curled" },
        { word: "TROUT",    hint: "River's silver flash" },
        { word: "SEALS",    hint: "Playful pinnipeds" },
        { word: "PERCH",    hint: "A fish or a place to sit" },
        { word: "ABYSS",    hint: "The deepest dark" },
        { word: "DEPTHS",   hint: "The deep ocean layers" },
        { word: "BUOY",     hint: "It floats to guide you" },
        { word: "ANCHOR",   hint: "Holds a ship in place" },
        { word: "LAGOON",   hint: "A calm coastal pool" },
        { word: "CREST",    hint: "Top of a wave" },
        { word: "TIDAL",    hint: "Relating to the tide" },
        { word: "BRINE",    hint: "Salty water" },
        { word: "SURGE",    hint: "A powerful wave push" },
        { word: "PLANKTON", hint: "The ocean's invisible food source" },
        { word: "ATOLL",    hint: "Circular coral island" },
        { word: "MARLIN",   hint: "A fast billfish" },
        { word: "NAUTILUS", hint: "Spiral-shelled cephalopod" },
        { word: "URCHIN",   hint: "Spiny sea floor dweller" },
        { word: "CLAM",     hint: "Lives inside two shells" },
        { word: "OCTOPUS",  hint: "Eight-armed escape artist" },
        { word: "MUSSEL",   hint: "Black-shelled bivalve" },
        { word: "LOBSTER",  hint: "Armoured ocean crawler" },
        { word: "DOLPHIN",  hint: "Acrobatic ocean mammal" },
        { word: "ALBATROSS",hint: "Giant ocean-roaming seabird" },
        { word: "STINGRAY", hint: "Flat and venomous" },
        { word: "WALRUS",   hint: "Tusked Arctic marine mammal" },
        { word: "PELICAN",  hint: "Bird with a pouch bill" },
        { word: "HERRING",  hint: "Small silvery schooling fish" },
        { word: "BARNACLE", hint: "It clings to rocks and hulls" },
        { word: "SEAGRASS", hint: "Meadows on the ocean floor" },
        { word: "SPONGE",   hint: "Simple porous sea creature" },
        { word: "SEAHORSE", hint: "Male gives birth here" },
        { word: "MORAY",    hint: "Eel lurking in a reef crevice" },
        { word: "TIDELINE", hint: "Mark left by receding water" },
        { word: "FATHOM",   hint: "Six feet of ocean depth" },
        { word: "WHIRLPOOL",hint: "A spinning vortex of water" },
        { word: "SIREN",    hint: "Mythical creature of the sea" },
        { word: "CUTTLEFISH",hint: "Master of colour-changing camouflage" },
        { word: "STARFISH", hint: "Five-armed reef wanderer" },
        { word: "BLOWHOLE", hint: "A whale breathes through this" },
        { word: "SPAWNING", hint: "Fish releasing eggs in water" },
        { word: "SALINITY", hint: "How salty the sea is" },
        { word: "FLIPPER",  hint: "A seal's paddling limb" },
        { word: "BALEEN",   hint: "Filter system in a whale's mouth" },
        { word: "ESTUARY",  hint: "Where a river widens to meet the sea" },
      ],
    },
    {
      id: "food",
      name: "Food",
      emoji: "🍜",
      hint: "What's on the plate",
      words: [
        { word: "MANGO",    hint: "Tropical king" },
        { word: "LEMON",    hint: "Puckering citrus" },
        { word: "BREAD",    hint: "Baked daily" },
        { word: "SPICE",    hint: "Adds the heat" },
        { word: "CURRY",    hint: "South Asian staple" },
        { word: "SUSHI",    hint: "Japanese rice art" },
        { word: "PASTA",    hint: "Italian staple" },
        { word: "TACOS",    hint: "Folded and filled" },
        { word: "PIZZA",    hint: "Round, cheesy, perfect" },
        { word: "OLIVE",    hint: "Mediterranean gem" },
        { word: "BASIL",    hint: "Herb of summer" },
        { word: "CACAO",    hint: "Chocolate's origin" },
        { word: "BROTH",    hint: "A warming liquid base" },
        { word: "DOUGH",    hint: "Before it's baked" },
        { word: "FEAST",    hint: "A grand meal" },
        { word: "GLAZE",    hint: "A shiny sweet coating" },
        { word: "NUTMEG",   hint: "Warm baking spice" },
        { word: "SAMBAL",   hint: "Chilli condiment" },
        { word: "SORBET",   hint: "Frozen fruit dessert" },
        { word: "LENTIL",   hint: "Protein-rich pulse" },
        { word: "WAFFLE",   hint: "Grid-patterned breakfast treat" },
        { word: "MISO",     hint: "Japanese fermented paste" },
        { word: "CREPE",    hint: "A thin French pancake" },
        { word: "GYOZA",    hint: "Japanese pan-fried dumpling" },
        { word: "FALAFEL",  hint: "Fried chickpea ball" },
        { word: "RISOTTO",  hint: "Creamy Italian rice dish" },
        { word: "KIMCHI",   hint: "Fermented Korean cabbage" },
        { word: "CHURRO",   hint: "Fried dough with cinnamon sugar" },
        { word: "BRIOCHE",  hint: "Rich buttery French bread" },
        { word: "TEMPURA",  hint: "Japanese light-battered frying" },
        { word: "HUMMUS",   hint: "Blended chickpea dip" },
        { word: "PAPAYA",   hint: "Orange tropical fruit" },
        { word: "TRUFFLE",  hint: "Luxury underground fungus" },
        { word: "SAFFRON",  hint: "The world's most costly spice" },
        { word: "TAPIOCA",  hint: "Starchy cassava pearls" },
        { word: "TAHINI",   hint: "Ground sesame paste" },
        { word: "GNOCCHI",  hint: "Little Italian potato dumplings" },
        { word: "RAMBUTAN", hint: "Hairy tropical fruit" },
        { word: "ANISE",    hint: "Liquorice-flavoured seed" },
        { word: "CHEDDAR",  hint: "Classic English hard cheese" },
        { word: "VENISON",  hint: "Deer meat" },
        { word: "PROSCIUTTO",hint: "Italian dry-cured ham" },
        { word: "QUINOA",   hint: "Protein-rich ancient grain" },
        { word: "EDAMAME",  hint: "Young soybeans in a pod" },
        { word: "CHUTNEY",  hint: "Spiced fruit or vegetable relish" },
        { word: "CARDAMOM", hint: "Aromatic green spice pod" },
        { word: "POLENTA",  hint: "Cornmeal porridge from Italy" },
        { word: "FETA",     hint: "Crumbly Greek white cheese" },
        { word: "CLOVE",    hint: "Spice used in mulled wine" },
        { word: "MARMALADE",hint: "Citrus preserve on toast" },
      ],
    },
    {
      id: "space",
      name: "Space",
      emoji: "🪐",
      hint: "Beyond our atmosphere",
      words: [
        { word: "ORBIT",    hint: "A path around a star" },
        { word: "LUNAR",    hint: "Relating to the moon" },
        { word: "COMET",    hint: "An icy visitor" },
        { word: "SOLAR",    hint: "Powered by the sun" },
        { word: "DWARF",    hint: "A smaller type of star or planet" },
        { word: "NOVA",     hint: "A star's sudden brightening" },
        { word: "QUASAR",   hint: "Extremely bright galactic core" },
        { word: "NEBULA",   hint: "A cloud of gas in space" },
        { word: "SATURN",   hint: "Planet with rings" },
        { word: "PULSAR",   hint: "A rotating neutron star" },
        { word: "METEOR",   hint: "A shooting star" },
        { word: "COSMOS",   hint: "The whole universe" },
        { word: "ZENITH",   hint: "Highest point in the sky" },
        { word: "VACUUM",   hint: "Empty space has no air" },
        { word: "PHOTON",   hint: "A particle of light" },
        { word: "ECLIPSE",  hint: "One body blocking another" },
        { word: "GRAVITY",  hint: "What keeps you down" },
        { word: "HORIZON",  hint: "Where sky meets ground" },
        { word: "AURORA",   hint: "Lights that dance near the poles" },
        { word: "CRATER",   hint: "A bowl left by an impact" },
        { word: "GALAXY",   hint: "A vast system of stars" },
        { word: "ASTEROID", hint: "Rocky body orbiting the sun" },
        { word: "WORMHOLE", hint: "A theoretical shortcut in space" },
        { word: "PARALLAX", hint: "Apparent shift due to viewing angle" },
        { word: "TRANSIT",  hint: "A planet crossing the sun's face" },
        { word: "APOGEE",   hint: "Farthest point from Earth in orbit" },
        { word: "PERIGEE",  hint: "Closest point to Earth in orbit" },
        { word: "SOLSTICE", hint: "The longest or shortest day" },
        { word: "EQUINOX",  hint: "Equal day and night" },
        { word: "SINGULARITY", hint: "The infinitely dense heart of a black hole" },
        { word: "INFRARED", hint: "Light we feel as heat" },
        { word: "SPECTRUM",  hint: "The full range of light wavelengths" },
        { word: "DOPPLER",   hint: "Effect that reveals a star's movement" },
        { word: "ANTIMATTER",hint: "Matter's opposite counterpart" },
        { word: "REDSHIFT",  hint: "Light stretched by an expanding universe" },
        { word: "UMBRA",     hint: "The darkest part of a shadow" },
        { word: "PENUMBRA",  hint: "The partial shadow at eclipse's edge" },
        { word: "CASSINI",   hint: "Famous Saturn-orbiting spacecraft" },
        { word: "VOYAGER",   hint: "Spacecraft that left the solar system" },
        { word: "HUBBLE",    hint: "Famous space telescope" },
        { word: "EXOPLANET", hint: "A planet orbiting another star" },
        { word: "SUPERNOVA", hint: "A star's explosive death" },
        { word: "IONOSPHERE",hint: "Upper atmosphere layer that reflects radio waves" },
        { word: "MAGNETAR",  hint: "Neutron star with extreme magnetic field" },
        { word: "PERIHELION",hint: "Closest point to the sun in an orbit" },
        { word: "ALBEDO",    hint: "How much light a surface reflects" },
        { word: "PARSEC",    hint: "Unit of cosmic distance" },
        { word: "MILKYWAY",  hint: "Our home galaxy's name" },
        { word: "BLACKHOLE", hint: "Where not even light escapes" },
        { word: "STARDUST",  hint: "What we're all made of" },
      ],
    },
    {
      id: "animals",
      name: "Animals",
      emoji: "🦁",
      hint: "The animal kingdom",
      words: [
        { word: "TIGER",    hint: "Striped big cat" },
        { word: "EAGLE",    hint: "King of the sky" },
        { word: "OTTER",    hint: "Playful river acrobat" },
        { word: "BISON",    hint: "Great Plains giant" },
        { word: "PANDA",    hint: "Black and white muncher" },
        { word: "RAVEN",    hint: "Edgar's favourite bird" },
        { word: "LEMUR",    hint: "Madagascar's primate" },
        { word: "TAPIR",    hint: "Odd-nosed forest dweller" },
        { word: "VIPER",    hint: "Venomous serpent" },
        { word: "FINCH",    hint: "Darwin's muse" },
        { word: "GECKO",    hint: "Wall-climbing lizard" },
        { word: "HIPPO",    hint: "River horse" },
        { word: "MOOSE",    hint: "Antlered lake-wader" },
        { word: "KOALA",    hint: "Eucalyptus enthusiast" },
        { word: "QUAIL",    hint: "Ground-nesting bird" },
        { word: "MANTA",    hint: "Gentle ocean glider" },
        { word: "CRANE",    hint: "Long-legged dancer" },
        { word: "WOMBAT",   hint: "Australian burrower" },
        { word: "JAGUAR",   hint: "Spotted rainforest cat" },
        { word: "STOAT",    hint: "Small, fast, fearless weasel" },
        { word: "LYNX",     hint: "Tufted-eared wild cat" },
        { word: "CONDOR",   hint: "Giant Andean vulture" },
        { word: "BLOBFISH", hint: "Deep-sea droopy creature" },
        { word: "ARMADILLO",hint: "Armoured desert mammal" },
        { word: "MONGOOSE", hint: "Snake's speedy rival" },
        { word: "PANGOLIN", hint: "Scaly anteater" },
        { word: "PLATYPUS", hint: "Egg-laying mammal with a duck bill" },
        { word: "CAPYBARA", hint: "World's largest rodent" },
        { word: "AXOLOTL",  hint: "Salamander that never grows up" },
        { word: "NARWHAL",  hint: "Unicorn of the sea" },
        { word: "CHAMELEON",hint: "Master of colour change" },
        { word: "HAMSTER",  hint: "Cheeky-pouched cage runner" },
        { word: "PEACOCK",  hint: "Bird with a spectacular tail fan" },
        { word: "GORILLA",  hint: "Largest living primate" },
        { word: "CHEETAH",  hint: "Fastest land animal" },
        { word: "PIRANHA",  hint: "Ferocious freshwater fish" },
        { word: "VULTURE",  hint: "Nature's clean-up crew" },
        { word: "IBIS",     hint: "Long-billed wading bird" },
        { word: "FERRET",   hint: "Slender domesticated mustelid" },
        { word: "HYENA",    hint: "Spotted laughing scavenger" },
        { word: "GAZELLE",  hint: "Graceful African sprinter" },
        { word: "PUFFIN",   hint: "Colourful-billed seabird" },
        { word: "MANDRILL", hint: "Brightly faced forest baboon" },
        { word: "SLOTH",    hint: "World's slowest mammal" },
        { word: "HORNBILL", hint: "Bird with a casque on its bill" },
        { word: "WOLVERINE",hint: "Fierce forest mustelid" },
        { word: "OCELOT",   hint: "Small spotted wild cat" },
        { word: "FLAMINGO", hint: "Pink bird that stands on one leg" },
        { word: "MANATEE",  hint: "Gentle sea cow" },
        { word: "KOMODO",   hint: "World's largest lizard" },
      ],
    },
    {
      id: "travel",
      name: "Travel",
      emoji: "✈️",
      hint: "Places and journeys",
      words: [
        { word: "COAST",    hint: "Where land meets sea" },
        { word: "PLAZA",    hint: "A town square" },
        { word: "TRAIL",    hint: "A path to follow" },
        { word: "FJORD",    hint: "Norwegian inlet" },
        { word: "OASIS",    hint: "Desert refuge" },
        { word: "VISTA",    hint: "A beautiful view" },
        { word: "BAZAAR",   hint: "An open-air market" },
        { word: "HOSTEL",   hint: "Budget traveller's home" },
        { word: "HARBOR",   hint: "Where ships rest" },
        { word: "SAFARI",   hint: "An African wildlife trip" },
        { word: "GORGE",    hint: "A deep canyon" },
        { word: "ROUTE",    hint: "The path you take" },
        { word: "DUNES",    hint: "Rolling sand hills" },
        { word: "TEMPLE",   hint: "A place of worship" },
        { word: "VOYAGE",   hint: "A long sea journey" },
        { word: "PEAK",     hint: "Summit of a mountain" },
        { word: "COBBLE",   hint: "Old-town streets paved with stones" },
        { word: "BORDER",   hint: "Where one country ends" },
        { word: "LAYOVER",  hint: "A stop between flights" },
        { word: "PASSPORT", hint: "Your ticket across borders" },
        { word: "CUSTOMS",  hint: "Border entry inspection" },
        { word: "ITINERARY",hint: "Your planned travel schedule" },
        { word: "FUNICULAR",hint: "A cable-driven hillside railway" },
        { word: "RICKSHAW", hint: "A three-wheeled taxi" },
        { word: "GONDOLA",  hint: "Venice's iconic boat" },
        { word: "RUINS",    hint: "Ancient crumbled structures" },
        { word: "NOMAD",    hint: "One who wanders without a fixed home" },
        { word: "JETLAG",   hint: "Time-zone fatigue" },
        { word: "PENSION",  hint: "A small European guesthouse" },
        { word: "SOUVENIR", hint: "A keepsake from your trip" },
        { word: "WAYPOINT", hint: "A marked stop along a route" },
        { word: "DETOUR",   hint: "A route away from the main path" },
        { word: "EXCURSION",hint: "A short trip from your base" },
        { word: "BACKPACK", hint: "The traveller's carry-all" },
        { word: "LOUNGE",   hint: "Where you wait before a flight" },
        { word: "CANOE",    hint: "A paddled narrow boat" },
        { word: "SHRINE",   hint: "A sacred site to visit" },
        { word: "CANYON",   hint: "A deep river-carved valley" },
        { word: "BUNGALOW", hint: "A low single-storey stay" },
        { word: "TERRACED", hint: "Stepped hillside fields or streets" },
        { word: "MINARET",  hint: "Tall tower of a mosque" },
        { word: "ARCHIPELAGO", hint: "A group of islands" },
        { word: "PENINSULA",hint: "Land surrounded by water on three sides" },
        { word: "VISA",     hint: "Permission to enter a country" },
        { word: "ALTITUDE", hint: "Height above sea level" },
        { word: "CARAVANSARY", hint: "Ancient inn for trading caravans" },
        { word: "HAMLET",   hint: "A tiny village" },
        { word: "STEPPE",   hint: "A vast flat treeless plain" },
        { word: "PORTAGE",  hint: "Carrying a boat between waterways" },
        { word: "MERIDIAN", hint: "A longitude line around the Earth" },
      ],
    },
    {
      id: "programming",
      name: "Programming",
      emoji: "💻",
      hint: "Code, logic, and tech",
      words: [
        { word: "ARRAY",    hint: "An ordered list of values" },
        { word: "LOOP",     hint: "Repeats a block of code" },
        { word: "CLASS",    hint: "A blueprint for objects" },
        { word: "DEBUG",    hint: "Find and fix the bug" },
        { word: "STACK",    hint: "Last in, first out structure" },
        { word: "QUEUE",    hint: "First in, first out structure" },
        { word: "TOKEN",    hint: "A unit of parsed code" },
        { word: "PARSE",    hint: "Break input into meaningful parts" },
        { word: "CACHE",    hint: "Store data for faster access" },
        { word: "MERGE",    hint: "Combine two branches of code" },
        { word: "CLONE",    hint: "Copy a repository" },
        { word: "COMMIT",   hint: "Save a snapshot in version control" },
        { word: "BRANCH",   hint: "A diverging line of development" },
        { word: "DEPLOY",   hint: "Release code to production" },
        { word: "SYNTAX",   hint: "The rules of a language's grammar" },
        { word: "SCOPE",    hint: "Where a variable is visible" },
        { word: "THREAD",   hint: "A unit of concurrent execution" },
        { word: "MUTEX",    hint: "Prevents two threads clashing" },
        { word: "KERNEL",   hint: "Core of an operating system" },
        { word: "SOCKET",   hint: "Endpoint for network communication" },
        { word: "POINTER",  hint: "A variable storing a memory address" },
        { word: "BUFFER",   hint: "Temporary storage for data in transit" },
        { word: "PACKET",   hint: "A unit of data sent over a network" },
        { word: "BINARY",   hint: "Base-2 number system" },
        { word: "HEXADECIMAL", hint: "Base-16 number system" },
        { word: "BOOLEAN",  hint: "True or false, nothing else" },
        { word: "FUNCTION", hint: "A reusable block of code" },
        { word: "RUNTIME",  hint: "When the program is executing" },
        { word: "COMPILE",  hint: "Translate code to machine language" },
        { word: "REFACTOR", hint: "Improve code without changing behaviour" },
        { word: "RECURSION",hint: "A function that calls itself" },
        { word: "CLOSURE",  hint: "A function that captures its scope" },
        { word: "LAMBDA",   hint: "An anonymous inline function" },
        { word: "ITERATOR", hint: "Steps through a collection one by one" },
        { word: "PIPELINE", hint: "Data flowing through linked stages" },
        { word: "WEBHOOK",  hint: "A callback triggered by an event" },
        { word: "ENDPOINT", hint: "A URL that handles API requests" },
        { word: "SCHEMA",   hint: "Blueprint of a database structure" },
        { word: "QUERY",    hint: "A request sent to a database" },
        { word: "INDEX",    hint: "Speeds up database lookups" },
        { word: "FIREWALL", hint: "Blocks unauthorised network access" },
        { word: "ENCRYPT",  hint: "Scramble data for security" },
        { word: "HASHING",  hint: "Turning data into a fixed-length digest" },
        { word: "PAYLOAD",  hint: "The actual data in a request" },
        { word: "LATENCY",  hint: "The delay in data transmission" },
        { word: "DAEMON",   hint: "A background process on a server" },
        { word: "REGEX",    hint: "Pattern-matching for text" },
        { word: "LINTING",  hint: "Automated code style checking" },
        { word: "TESTING",  hint: "Verifying code does what it should" },
        { word: "AGILE",    hint: "An iterative software development method" },
      ],
    },
    {
      id: "gaming",
      name: "Gaming",
      emoji: "🎮",
      hint: "Press start to begin",
      words: [
        { word: "QUEST",    hint: "A mission to complete" },
        { word: "LOOT",     hint: "Rewards from defeated enemies" },
        { word: "SPAWN",    hint: "Where you appear in the world" },
        { word: "BOSS",     hint: "The big enemy at level's end" },
        { word: "FACTION",  hint: "A group of players banding together" },
        { word: "AVATAR",   hint: "Your in-game character" },
        { word: "PIXEL",    hint: "The smallest unit of a screen" },
        { word: "CHEAT",    hint: "A secret code for an advantage" },
        { word: "HEALTH",   hint: "Your remaining life points" },
        { word: "SHIELD",   hint: "Blocks incoming damage" },
        { word: "STEALTH",  hint: "Moving unseen by enemies" },
        { word: "RESPAWN",  hint: "Coming back to life after death" },
        { word: "GLITCH",   hint: "A bug that changes gameplay" },
        { word: "ARCADE",   hint: "Classic coin-operated gaming hall" },
        { word: "JOYSTICK", hint: "An analogue input controller" },
        { word: "DUNGEON",  hint: "A dangerous underground level" },
        { word: "POTION",   hint: "Drinkable item that restores health" },
        { word: "CRAFTING", hint: "Building items from raw materials" },
        { word: "SANDBOX",  hint: "Open-world with no fixed path" },
        { word: "TUTORIAL", hint: "The beginner's learning level" },
        { word: "HITBOX",   hint: "The invisible collision area" },
        { word: "PUZZLE",   hint: "A challenge solved with logic" },
        { word: "CUTSCENE", hint: "A cinematic break in gameplay" },
        { word: "LOADING",  hint: "Please wait while the world prepares" },
        { word: "RENDER",   hint: "Drawing the game world on screen" },
        { word: "TEXTURE",  hint: "The surface appearance of a 3D object" },
        { word: "RAGDOLL",  hint: "Physics-based character collapse" },
        { word: "SPEEDRUN", hint: "Completing a game as fast as possible" },
        { word: "GRINNING", hint: "Earning XP through repetitive play" },
        { word: "EXPLOIT",  hint: "A gameplay trick that breaks the rules" },
        { word: "CONSOLE",  hint: "A dedicated gaming machine" },
        { word: "EMULATOR", hint: "Software mimicking old hardware" },
        { word: "CARTRIDGE",hint: "Game stored on a removable chip" },
        { word: "LEADERBOARD",hint: "Ranking players by high score" },
        { word: "MATCHMAKING",hint: "Pairing players of similar skill" },
        { word: "INVENTORY", hint: "Your bag of collected items" },
        { word: "CHECKPOINT",hint: "A saved progress marker mid-level" },
        { word: "MINIBOSS",  hint: "A smaller but still tough enemy" },
        { word: "MMORPG",   hint: "Massively multiplayer online role-play" },
        { word: "ESPORTS",  hint: "Competitive gaming as a sport" },
        { word: "PATCH",    hint: "An update that fixes game issues" },
        { word: "MODDING",  hint: "Fan-made changes to a game" },
        { word: "PLATFORM", hint: "A game where you jump between surfaces" },
        { word: "ROGUE",    hint: "A randomly generated dungeon game" },
        { word: "TURNBASED",hint: "Each player acts in sequence" },
        { word: "MECHANIC", hint: "A core rule of how the game works" },
        { word: "DIALOGUE", hint: "Spoken conversation with an NPC" },
        { word: "OVERWORLD",hint: "The main map connecting game areas" },
        { word: "TROPHY",   hint: "An achievement reward" },
        { word: "NOCLIP",   hint: "Cheat that lets you walk through walls" },
      ],
    },
    {
      id: "sports",
      name: "Sports",
      emoji: "⚽",
      hint: "Game on",
      words: [
        { word: "GOAL",     hint: "Score one to win" },
        { word: "SPRINT",   hint: "Run as fast as you can" },
        { word: "TACKLE",   hint: "Stop the ball carrier" },
        { word: "MATCH",    hint: "A competitive game between two sides" },
        { word: "REFEREE",  hint: "The one who enforces the rules" },
        { word: "FOUL",     hint: "A rule-breaking action" },
        { word: "OFFSIDE",  hint: "Illegal position in football" },
        { word: "DRIBBLE",  hint: "Moving with the ball" },
        { word: "PENALTY",  hint: "A free kick or shot for an infraction" },
        { word: "INNINGS",  hint: "A cricket team's batting turn" },
        { word: "WICKET",   hint: "What a cricket bowler aims for" },
        { word: "STUMPED",  hint: "Dismissed behind the crease" },
        { word: "SCRUM",    hint: "Rugby's contested restart" },
        { word: "LINEOUT",  hint: "Rugby's throw-in from the sideline" },
        { word: "HALFBACK", hint: "A midfield rugby position" },
        { word: "DEUCE",    hint: "40-40 in tennis" },
        { word: "SMASH",    hint: "A powerful overhead tennis shot" },
        { word: "ACE",      hint: "An unreturnable serve" },
        { word: "VOLLEY",   hint: "Hitting the ball before it bounces" },
        { word: "BIRDIE",   hint: "One under par in golf" },
        { word: "BOGEY",    hint: "One over par in golf" },
        { word: "CADDIE",   hint: "A golfer's bag carrier and advisor" },
        { word: "RELAY",    hint: "A team race with baton passing" },
        { word: "BATON",    hint: "Passed between relay runners" },
        { word: "JAVELIN",  hint: "Thrown in an athletic field event" },
        { word: "DISCUS",   hint: "A spinning throw in athletics" },
        { word: "HURDLES",  hint: "Barriers to jump over in a race" },
        { word: "MARATHON", hint: "A 26.2 mile road race" },
        { word: "SLALOM",   hint: "A ski race through gates" },
        { word: "MOGULS",   hint: "Bumpy terrain ski event" },
        { word: "HALFPIPE", hint: "A U-shaped ramp for snowboarders" },
        { word: "ROWING",   hint: "A sport on the water with oars" },
        { word: "REGATTA",  hint: "A series of boat races" },
        { word: "KAYAK",    hint: "A small paddled boat" },
        { word: "FENCING",  hint: "Sword-fighting as a sport" },
        { word: "JUDO",     hint: "Japanese throwing martial art" },
        { word: "KARATE",   hint: "Strike-based Japanese martial art" },
        { word: "SQUASH",   hint: "A racket sport inside a walled court" },
        { word: "BADMINTON",hint: "A game played with a shuttlecock" },
        { word: "NETBALL",  hint: "Shooting through a high hoop without a board" },
        { word: "HANDBALL", hint: "Throw and catch team goal sport" },
        { word: "ARCHERY",  hint: "Hitting a target with arrows" },
        { word: "TRIATHLON",hint: "Swim, bike, run in sequence" },
        { word: "DECATHLON",hint: "Ten track and field events" },
        { word: "VELODROME",hint: "A banked indoor cycling track" },
        { word: "KNOCKOUT", hint: "Winning by ending the fight" },
        { word: "PODIUM",   hint: "Where the top three stand" },
        { word: "OVERTIME", hint: "Extra time when scores are level" },
        { word: "OFFBREAK", hint: "A spin delivery in cricket" },
        { word: "GRIDIRON", hint: "American football's playing field" },
      ],
    },
    {
      id: "random",
      name: "Random",
      emoji: "🎲",
      hint: "Anything goes",
      words: [
        { word: "CIPHER",   hint: "A secret coded message" },
        { word: "VELVET",   hint: "A soft plush fabric" },
        { word: "LANTERN",  hint: "A portable light source" },
        { word: "WITHER",   hint: "To dry up and decay" },
        { word: "MIRAGE",   hint: "An optical illusion in the heat" },
        { word: "ANVIL",    hint: "A blacksmith's heavy block" },
        { word: "COBWEB",   hint: "Abandoned spider's work" },
        { word: "PENDULUM", hint: "A swinging timekeeping weight" },
        { word: "QUARRY",   hint: "Where stone is cut from the earth" },
        { word: "LOCKET",   hint: "A small hinged pendant" },
        { word: "PRISM",    hint: "Splits light into a rainbow" },
        { word: "GALLEON",  hint: "A large old sailing warship" },
        { word: "MYTH",     hint: "A traditional story of the ancient world" },
        { word: "OMEN",     hint: "A sign of things to come" },
        { word: "RELIC",    hint: "An old surviving object" },
        { word: "LABYRINTH",hint: "A complex network of paths" },
        { word: "SCROLL",   hint: "Ancient rolled-up writing" },
        { word: "GOBLET",   hint: "A fancy drinking cup" },
        { word: "VERDICT",  hint: "A court's final decision" },
        { word: "ENIGMA",   hint: "Something mysterious and puzzling" },
        { word: "MOSAIC",   hint: "Art made from tiny tiles" },
        { word: "PARADOX",  hint: "A self-contradicting truth" },
        { word: "EPOCH",    hint: "A distinct period in history" },
        { word: "HERALD",   hint: "A messenger who announces news" },
        { word: "TURRET",   hint: "A small tower on a castle wall" },
        { word: "DYNASTY",  hint: "A line of ruling rulers from one family" },
        { word: "QUORUM",   hint: "Minimum members needed for a vote" },
        { word: "PLINTH",   hint: "The base a statue stands on" },
        { word: "CODEX",    hint: "An ancient bound book" },
        { word: "BALLOT",   hint: "A slip used for voting" },
        { word: "LEDGER",   hint: "A book of financial accounts" },
        { word: "CHARTER",  hint: "An official founding document" },
        { word: "DECREE",   hint: "An official order with force of law" },
        { word: "STATUTE",  hint: "A written law passed by legislature" },
        { word: "GUILD",    hint: "A medieval craftsmen's association" },
        { word: "PARCHMENT",hint: "Animal-skin writing surface" },
        { word: "SIGIL",    hint: "A magical symbol or seal" },
        { word: "MONOLITH", hint: "A single massive upright stone" },
        { word: "TAPESTRY", hint: "A woven fabric wall hanging" },
        { word: "SCEPTRE",  hint: "A royal ceremonial staff" },
        { word: "CATAPULT", hint: "Ancient siege weapon that hurls stones" },
        { word: "SUNDIAL",  hint: "Tells time using shadow and sun" },
        { word: "CAMEO",    hint: "A small carved relief portrait" },
        { word: "FRESCO",   hint: "Painting done on wet plaster" },
        { word: "GARGOYLE", hint: "A carved stone spout on a church" },
        { word: "ORACLE",   hint: "A prophet of ancient wisdom" },
        { word: "BELFRY",   hint: "Where church bells are hung" },
        { word: "ESCUTCHEON",hint: "A heraldic shield design" },
        { word: "TROUBADOUR",hint: "A medieval wandering poet-musician" },
        { word: "JOUSTING", hint: "Knights charging at each other on horseback" },
      ],
    },
  ],

  // ── WORD OF THE DAY ──────────────────────
  // One per calendar day, seeded by date.
  // These words must NOT appear in any topic above.
  dailyWords: [
    { word: "TIDE",    hint: "The ocean breathes in and out" },
    { word: "DRIFT",   hint: "What currents do to lost things" },
    { word: "PEARL",   hint: "Born inside an oyster's pain" },
    { word: "FLOAT",   hint: "To rest on water's surface" },
    { word: "SHORE",   hint: "Where the tide says goodbye" },
    { word: "SWELL",   hint: "A long, gentle wave from afar" },
    { word: "WRACK",   hint: "Seaweed left by the tide" },
    { word: "BASIN",   hint: "Where ocean water collects" },
    { word: "EDDY",    hint: "Water spinning in a circle" },
    { word: "HAVEN",   hint: "A safe harbour from storms" },
    { word: "WAKE",    hint: "The trail a boat leaves behind" },
    { word: "CURRENT", hint: "The ocean's invisible river" },
    { word: "MARINA",  hint: "A harbour for small boats" },
    { word: "SERAPH",  hint: "An ocean's guardian spirit" },
    { word: "MANTLE",  hint: "The layer under the ocean floor" },
    { word: "GROTTO",  hint: "A sea cave, cool and quiet" },
    { word: "FOSSIL",  hint: "A creature frozen in stone time" },
    { word: "SPIRAL",  hint: "How a nautilus shell grows" },
    { word: "RIPPLE",  hint: "A small wave spreading outward" },
    { word: "ABYSSAL", hint: "Relating to the deepest ocean zone" },
    { word: "TRAWL",   hint: "A drag-net through the sea" },
    { word: "PLUME",   hint: "A rising column in the ocean" },
    { word: "BILLOW",  hint: "A rolling, swelling wave" },
    { word: "MOORING", hint: "A fixed point to tie a boat" },
    { word: "KNOT",    hint: "A sailor's unit of speed" },
    { word: "ZEPHYR",  hint: "A gentle west wind over the water" },
    { word: "SHOALING",hint: "Waves growing shallower near shore" },
    { word: "NEAP",    hint: "A weak tide between springs" },
    { word: "ISLET",   hint: "A very small island" },
    { word: "LIMPET",  hint: "A shellfish that clings to rocks" },
  ],
};

// ── UTILITY: Get today's Word of the Day ──
// Index is determined by days elapsed since 2026-01-01, wrapping the list.
function getDailyWord() {
  const now      = new Date();
  const dayIndex = Math.floor(
    (Date.UTC(now.getFullYear(), now.getMonth(), now.getDate()) - Date.UTC(2026, 0, 1)) / 86400000
  ) % WORD_DB.dailyWords.length;

  return {
    ...WORD_DB.dailyWords[Math.abs(dayIndex)],
    topic:     "special",
    topicName: "Word of the Day",
  };
}

// ── UTILITY: Get a random word for a specific topic ──
// Fully random each time so replaying a topic always gives a fresh word.
// The Word of the Day (getDailyWord) remains date-seeded and consistent.
function getWordFromTopic(topicId) {
  const topic = WORD_DB.topics.find(t => t.id === topicId);
  if (!topic) return null;

  const idx = Math.floor(Math.random() * topic.words.length);

  return {
    ...topic.words[idx],
    topic:     topicId,
    topicName: topic.name,
  };
}

// ── UTILITY: Quick-lookup set for valid game words ──
// Used by game.js to reject nonsense guesses without a full dictionary.
// Built lazily on first access.
let _validWordSet = null;

function getValidWordSet() {
  if (_validWordSet) return _validWordSet;

  _validWordSet = new Set();

  // Add all topic words
  WORD_DB.topics.forEach(topic => {
    topic.words.forEach(w => _validWordSet.add(w.word.toUpperCase()));
  });

  // Add all daily words
  WORD_DB.dailyWords.forEach(w => _validWordSet.add(w.word.toUpperCase()));

  return _validWordSet;
}